PianoVillage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from piano_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^piano_app/',include('piano_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),

]

piano_app/urls.py
from django.conf.urls import url
from piano_app import views

app_name = 'piano_app'

urlpatterns = [
    url(r'^about',views.about, name='about'),
    url(r'^applications',views.applications, name='applications'),
    url(r'^base',views.base, name='base'),
    url(r'^community',views.community, name='community'),
    url(r'^competitions',views.competitions, name='competitions'),
    url(r'^contacts',views.contacts, name='contacts'),
    url(r'^donation',views.donation, name='donation'),
    url(r'^members',views.members, name='members'),
    url(r'^news',views.news, name='news'),
    url(r'^participation',views.participation, name='participation'),
    url(r'^philosophy',views.philosophy, name='philosophy'),
    url(r'^platform',views.platform, name='platform'),
    url(r'^prize',views.prize, name='prize'),
    url(r'^program',views.program, name='program'),
    url(r'^signup',views.signup, name='signup'),
    url(r'^sponsors',views.sponsors, name='sponsors'),
    url(r'^thankyou',views.thankyou, name='thankyou'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

piano_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User)

    # Add any additional attributes you want
    date_of_birth = models.DateField(default='1987-04-27')
    SEX_CHOICES = (
        ('male','Male'),
        ('female','Female'),
        ('decline to identify','Decline to Identify')
    )
    sex = models.CharField(max_length=50, choices=SEX_CHOICES, default='decline to identify')
    school_name = models.CharField(max_length=50, default='Eshkol Academy')
    GRADE_CHOICES = (
        ('prek','Pre K'),
        ('kindergarten','Kindergarten'),
        ('first','First Grade'),
        ('second','Second Grade'),
        ('third','Third Grade'),
        ('forth','Fourth Grade'),
        ('fifth','Fifth Grade'),
        ('sixth','Sixth Grade'),
        ('seventh','Seventh Grade'),
        ('eighth','Eighth Grade'),
        ('ninth','Nineth Grade'),
        ('tenth','Tenth Grade'),
        ('eleventh','Eleventh Grade'),
        ('twelfth','Twelfth Grade'),
        ('adult','Adult'),
    )
    grade = models.CharField(max_length=50, choices=GRADE_CHOICES, default='prek')
    address1 = models.CharField(max_length=50, default='123 Fake St.')
    address2 = models.CharField(max_length=50, default='Apt 108')
    city = models.CharField(max_length=50, default='New York')
    state = models.CharField(max_length=50, default='New York')
    zip_code = models.CharField(max_length=5, default='12345')
    phone = models.CharField(max_length=10, default='9141234567')
    email = models.EmailField(max_length=200, default='example@gmail.com')
    volunteer_experience = models.TextField(max_length=5000, default='Previous volunteer experience')
    interest_in_piano_village = models.TextField(max_length=5000, default='I would like my child to learn how to play the piano')
    goals_for_service_to_the_community = models.TextField(max_length=5000, default='')
    emergency_name = models.CharField(max_length=10, default='John Smith')
    emergency_phone = models.CharField(max_length=10, default='9141234567')
    relationship = models.CharField(max_length=10, default='Father')
    HEAR_CHOICES = (
        ('friend','Friend'),
        ('parent','Parent'),
        ('website','Website'),
        ('media','Media'),
        ('other','Other'),
    )
    how_did_you_hear_about_us = models.CharField(max_length=50, choices=HEAR_CHOICES, default='media')

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

piano_app/forms.py
from django import forms
from django.contrib.auth.models import User
from piano_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('date_of_birth',
                  'sex',
                  'school_name',
                  'grade',
                  'address1',
                  'address2',
                  'city',
                  'state',
                  'zip_code',
                  'phone',
                  'email',
                  'volunteer_experience',
                  'interest_in_piano_village',
                  'goals_for_service_to_the_community',
                  'emergency_name',
                  'emergency_phone',
                  'relationship',
                  'how_did_you_hear_about_us')

piano_app/views.py
from django.shortcuts import render
from piano_app.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def about(request):
    return render(request, 'piano_app/about.html')

def applications(request):
    return render(request, 'piano_app/applications.html')

def base(request):
    return render(request, 'piano_app/base.html')

def community(request):
    return render(request, 'piano_app/community.html')

def competitions(request):
    return render(request, 'piano_app/competitions.html')

def contacts(request):
    return render(request, 'piano_app/contacts.html')

def donation(request):
    return render(request, 'piano_app/donation.html')

def index(request):
    return render(request, 'piano_app/index.html')

def members(request):
    return render(request, 'piano_app/members.html')

def news(request):
    return render(request, 'piano_app/news.html')

def participation(request):
    return render(request, 'piano_app/participation.html')

def philosophy(request):
    return render(request, 'piano_app/philosophy.html')

def platform(request):
    return render(request, 'piano_app/platform.html')

def prize(request):
    return render(request, 'piano_app/prize.html')

def program(request):
    return render(request, 'piano_app/program.html')

def signup(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'piano_app/signup.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def sponsors(request):
    return render(request, 'piano_app/sponsors.html')

def thankyou(request):
    return render(request, 'piano_app/thankyou.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'piano_app/login.html', {})

templates/piano_app/about.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
    {% block body_block%}
        <h1>About Us</h1>
        <h3>Who we are</h3>
        <p>We are parents, teachers, relatives, and friends who see tremendous opportunities to educate the whole child
        through piano instruction. Today, children, like bees, fly from activity to activity to develop different skills
        and learning strategies. There is often too much to do and not enough time. We support Felicia Feng Zhang’s
        breakthrough method for learning piano notation, music theory, reading skills, math skills, discipline, manners,
        and motor skills in a more effective and efficient way. Moreover, we believe that the well-rounded musician must
        cultivate skills in a community of pianists and experience from the earliest stages of piano instruction the joys
        of sharing in a mutual love of music.</p>
        <h3>Mission</h3>
        <p>Our mission is to cultivate a rich, deep, and lifelong enjoyment and appreciation of music and the arts from
        a young age; to build confidence, strengthen character, and encourage self-expression through music; to develop
        leadership skills as musicians and in academic pursuits; to engage family members, teachers, and friends as
        crucial supports of music education; and to cultivate core values in the hopes of shaping a more harmonious
        society.</p>
        <h3>Join Us</h3>
        <p>The Piano Village Foundation is for all ages, backgrounds, and nationalities.  Understanding how the piano
        enriches all aspects of life, we use this foundation as space for sharing our experiences, talents, and ideas
        about piano education, composition, and performance. We believe that piano is part of daily growth, and we this
        community provides encouragement through our challenges and celebration in our achievements.<br><br>For high school
        students: practice your leadership, share your talent with younger pianists, and meet peers.<br><br>For middle
        school and upper elementary students: learn to observe and work with role models. Let the creativity of others
        inspire your own. Consider how you may begin to mentor younger or newer students. <br><br> For parents: provide
        a model for your child. Demonstrate your passion for music, care for others, and focus. Reflect on what it means
        to be an educator and let the piano be a way to boost your energy and find spiritual growth.<br><br>For educators:
        the piano provides a starting point for a wide range of academic skills. We hope you will share your knowledge
        in and experience of the symbiotic relationship between piando education and academic study. </p>

    {% endblock %}

templates/piano_app/applications.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
    {% block body_block%}
        <h1>Applications</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    {% endblock %}

templates/piano_app/competitions.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Competitions</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{% endblock %}

templates/piano_app/donation.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Donation</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{% endblock %}

templates/piano_app/index.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
    {% block body_block%}

    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page</h1>

    {% endblock %}

templates/piano_app/login.html
{% extends 'piano_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'piano_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

templates/piano_app/members.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Members</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{% endblock %}

templates/piano_app/news.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>News</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{% endblock %}

templates/piano_app/participation.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Participation</h1>
    <ul>
        <li>Sponsor</li>
        <li>Volunteer</li>
        <li>Regional Coordinator</li>
        <li>Instructor</li>
        <li>Mentor</li>
    </ul>

{% endblock %}

templates/piano_app/philosophy.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Philosophy</h1>
    <ul>
        <li>Piano education should provide an innovative, efficient, and enjoyable way for young children
        to learn to read music notation and to play competently with both hands.</li>
        <li>An emphasis on focusing on the notation, following the instructor, and playing with flow empowers
        young pianists to make faster progress in their development.</li>
        <li>We should contribute to the musical education of others and serve in our communities as volunteers
        and leaders.</li>
        <li>We should employ our talents to reach out to underprivileged, vulnerable, or marginalized groups
        whenever possible.</li>
    </ul>
    <h3>What is Felicia3EFM?</h3>
    <p>3: Parents, Student, and Teacher form a triangular team. Across different learning stages, the three
    key terms represent the principle approach on that stage. For example:<br>E: Energy, Engage, Efficiency<br>
    F: Focus, Follow, Flow<br>M: Mindset, Manner, Motivation</p>
    <h3>Benefits of 3EFM and beyond piano learning</h3>
    <p>These words appears in different learning stages, student also learn these words and reinforce these
    words in connection with other subjects in life, academic and sports. </p>
    <ul>
        <li>Characteristic builder</li>
        <li>Appreciation taste</li>
        <li>EQ</li>
        <li>Sensation</li>
        <li>Intuition</li>
        <li>Mathematical Skills</li>
        <li>Comprehensive Listening</li>
        <li>Confident</li>
        <li>Coordination built from 2 to 6 ways at same time</li>
        <li>Multi tasking ability</li>
        <li>Cognitive Ability</li>
        <li>Speech</li>
        <li>Expression</li>
        <li>Focus</li>
        <li>Follow</li>
        <li>Flow</li>
        <li>Flexibility</li>
        <li>Discipline</li>
        <li>Steady Control Ability</li>
        <li>Challenge Taking</li>
        <li>Imitation</li>
        <li>Thinking Connection</li>
        <li>learning strategies</li>
        <li>Improvisation</li>
        <li>Transpose</li>
        <li>Memorization skills</li>
        <li>common core</li>
    </ul>

{% endblock %}

templates/piano_app/platform.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Platform</h1>
    <ul>
        <li>Parent-Student Forum</li>
        <li>Artistic Fellow-Student Forum</li>
        <li>Piano Doctor: assessment and diagnosis of piano technique</li>
    </ul>

{% endblock %}

templates/piano_app/prize.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Prize</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{% endblock %}

templates/piano_app/thankyou.html
<!DOCTYPE html>
{% extends "piano_app/base.html" %}
{% block body_block%}
    <h1>Thank you for signing up!</h1>

{% endblock %}